export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-8 text-neutral-200 text-sm leading-relaxed">
      <h2 className="text-xl font-semibold text-white mb-2">Terms of Service</h2>
      <p className="text-xs text-neutral-400 mb-6">Last updated: 28 April 2026</p>

      <section>
        <h3>1. Service Description</h3>
        <p>
          Election Analytics ("the Service") is an interactive platform for exploring Indian
          Assembly and General Election data, running prediction simulations, and sharing analytical
          scenarios with a community of users. The Service is provided on an "as-is" basis.
        </p>
      </section>

      <section>
        <h3>2. Prediction Simulator Disclaimer</h3>
        <p>
          <strong>
            The prediction simulator is a mathematical modelling tool, not an electoral forecast.
          </strong>{' '}
          Predictions are generated by applying user-configurable parameters (anti-incumbency
          percentage, turnout estimates, hypothetical new parties) to historical data. Results are
          illustrative simulations and should not be interpreted as predictions of actual election
          outcomes.
        </p>
        <p>
          The prediction simulator is <strong>not</strong> an exit poll, opinion poll, or any form
          of electoral survey within the meaning of the Representation of the People Act, 1951. It
          does not involve surveying voters or collecting data on voting intentions.
        </p>
      </section>

      <section>
        <h3>3. Data Attribution</h3>
        <p>
          Election data is sourced from the{' '}
          <a href="https://tcpd.ashoka.edu.in/" target="_blank" rel="noopener noreferrer">
            Trivedi Centre for Political Data (TCPD)
          </a>{' '}
          at Ashoka University, and from the Election Commission of India. All data is used with
          attribution and is not sold or redistributed as a standalone dataset.
        </p>
      </section>

      <section>
        <h3>4. Acceptable Use</h3>
        <p>You agree not to:</p>
        <ul>
          <li>
            Use the Service to generate or distribute content that is unlawful, defamatory, or
            misleading.
          </li>
          <li>Misrepresent prediction simulations as actual electoral forecasts or exit polls.</li>
          <li>Attempt to gain unauthorised access to other users' accounts or data.</li>
          <li>Use automated scripts to scrape data at rates that degrade service performance.</li>
          <li>Circumvent rate limits, access controls, or other security measures.</li>
        </ul>
      </section>

      <section>
        <h3>5. User Accounts</h3>
        <p>
          You are responsible for maintaining the security of your account. You must provide
          accurate contact information (mobile number) for authentication. You may delete your
          account at any time, which permanently removes all associated data.
        </p>
      </section>

      <section>
        <h3>6. Community Content</h3>
        <p>
          Prediction bookmarks shared publicly ("community predictions") remain your intellectual
          property. By making a bookmark public, you grant the Service a non-exclusive licence to
          display it within the community feed. You may make any public bookmark private or delete
          it at any time.
        </p>
      </section>

      <section>
        <h3>7. Subscriptions and Payments</h3>
        <p>
          Certain features may require a paid subscription. Subscription terms, pricing, and billing
          cycles will be clearly displayed before purchase. Payments are processed securely via
          third-party payment processors. Refund policies will be published alongside subscription
          offerings.
        </p>
      </section>

      <section>
        <h3>8. API Access</h3>
        <p>
          API keys, when available, are for programmatic access to the Service. API keys must not be
          shared publicly or embedded in client-side code. Usage limits apply per your subscription
          tier. We reserve the right to revoke API keys that violate acceptable use policies.
        </p>
      </section>

      <section>
        <h3>9. Limitation of Liability</h3>
        <p>
          To the maximum extent permitted by law, the Service is provided without warranties of any
          kind. We are not liable for decisions made based on prediction simulations or any data
          presented on the platform. We are not liable for service interruptions, data loss, or
          errors in the data.
        </p>
      </section>

      <section>
        <h3>10. Intellectual Property</h3>
        <p>
          The platform's source code is available under the MIT License. Election data is attributed
          to its original sources (TCPD, ECI). The Service's branding, design, and premium features
          may be subject to separate licensing terms.
        </p>
      </section>

      <section>
        <h3>11. Termination</h3>
        <p>
          We may suspend or terminate your account if you violate these terms. You may terminate
          your account at any time by deleting it. Upon termination, your data is handled in
          accordance with our Privacy Policy.
        </p>
      </section>

      <section>
        <h3>12. Changes to These Terms</h3>
        <p>
          We may update these terms from time to time. Material changes will be communicated via a
          notice on the platform. Continued use after changes constitutes acceptance of the updated
          terms.
        </p>
      </section>

      <section>
        <h3>13. Governing Law</h3>
        <p>
          These terms are governed by and construed in accordance with the laws of India. Any
          disputes shall be subject to the exclusive jurisdiction of the courts in India.
        </p>
      </section>
    </div>
  );
}
